"""core

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 21:30:11.656900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_log',
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('command', sa.String(length=100), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.Uuid(), nullable=False),
    sa.Column('supersedes', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_head', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('local_day', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_source', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retract_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['supersedes'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_chain_id'), 'event', ['chain_id'], unique=False)
    op.create_index('ix_event_day_kind', 'event', ['local_day', 'kind'], unique=False)
    op.create_index('uq_event_chain_head', 'event', ['chain_id'], unique=True, postgresql_where=sa.text('is_head'))
    op.create_index('uq_event_external_head', 'event', ['external_source', 'external_id'], unique=True, postgresql_where=sa.text('is_head AND external_id IS NOT NULL'))
    op.create_table('event_link',
    sa.Column('from_chain', sa.Uuid(), nullable=False),
    sa.Column('to_chain', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('from_chain', 'to_chain', 'relation')
    )
    op.create_table('food',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=300), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('unit_name', sa.String(length=32), nullable=True),
    sa.Column('unit_grams', sa.Double(), nullable=True),
    sa.Column('pack_grams', sa.Double(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('profile_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('height_cm', sa.Double(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('goal_weight_kg', sa.Double(), nullable=True),
    sa.Column('goal_date', sa.Date(), nullable=True),
    sa.Column('protein_g_per_kg', sa.Double(), nullable=False),
    sa.Column('fat_g_per_kg_min', sa.Double(), nullable=False),
    sa.Column('gym_sessions_per_week', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_version_valid_from'), 'profile_version', ['valid_from'], unique=False)
    op.create_table('recipe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_preference',
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('metric')
    )
    op.create_table('sync_state',
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('last_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('food_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('food_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kcal', sa.Double(), nullable=False),
    sa.Column('protein_g', sa.Double(), nullable=True),
    sa.Column('carbs_g', sa.Double(), nullable=True),
    sa.Column('fat_g', sa.Double(), nullable=True),
    sa.Column('fiber_g', sa.Double(), nullable=True),
    sa.Column('sugar_g', sa.Double(), nullable=True),
    sa.Column('salt_g', sa.Double(), nullable=True),
    sa.Column('source_note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_version_food_id'), 'food_version', ['food_id'], unique=False)
    op.create_table('recipe_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('serves', sa.Integer(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_version_recipe_id'), 'recipe_version', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_version_recipe_id'), table_name='recipe_version')
    op.drop_table('recipe_version')
    op.drop_index(op.f('ix_food_version_food_id'), table_name='food_version')
    op.drop_table('food_version')
    op.drop_table('sync_state')
    op.drop_table('source_preference')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_profile_version_valid_from'), table_name='profile_version')
    op.drop_table('profile_version')
    op.drop_table('food')
    op.drop_table('event_link')
    op.drop_index('uq_event_external_head', table_name='event', postgresql_where=sa.text('is_head AND external_id IS NOT NULL'))
    op.drop_index('uq_event_chain_head', table_name='event', postgresql_where=sa.text('is_head'))
    op.drop_index('ix_event_day_kind', table_name='event')
    op.drop_index(op.f('ix_event_chain_id'), table_name='event')
    op.drop_table('event')
    op.drop_table('command_log')
    # ### end Alembic commands ###
